### PR TITLE
Release descriptor 1.12.1

### PR DESCRIPTION
**Pull request by bertfrees**

### CODE REVIEW

**Comment by josteinaj** [comment]
The [URL referenced](https://github.com/daisy/pipeline-assembly/tree/gh-pages/releases) from the [Installation guide](http://daisy.github.io/pipeline/Get-Help/User-Guide/Installation/#updater) hasn't been updated with release descriptors since 1.10.4 it seems. Is it the wrong URL?

**Comment by bertfrees** [comment]
No, it's the right URL, but you can't use the updater to install any version. Version 1.12.1 will be the first since a while that you can update to.

**Comment by bertfrees** [comment]
Only from 1.12.0 though. I hope this is somehow ensured 🤔

**Comment by josteinaj** [comment]
I don't think that's ensured.

**Comment by bertfrees** [comment]
I was already afraid of that. The updater has a lot of shortcomings I think. It is just not practical to use at the moment.

**Pull request closed without merging**
