### PR TITLE
Release descriptors: added 1.14.2, 1.14.3, 1.14.4 and updated current to 1.14.4

### PR DESCRIPTION
**Pull request by josteinaj**

### CODE REVIEW

**Comment by bertfrees** [comment]
This replaces https://github.com/daisy/pipeline-assembly/pull/192, https://github.com/daisy/pipeline-assembly/pull/195 and https://github.com/daisy/pipeline-assembly/pull/198, right?

I think there is a reason why I did not merge these. I forgot what it was exactly, but it probably has to do with that configuration files and executables have changed after 1.14.0 and the updater [does not support it](https://github.com/daisy/pipeline-updater/issues/7). And probably also with the fact that the updater has too many [issues](https://github.com/daisy/pipeline-updater/issues) so that I prefer to not make new versions available through the updater than that people run into issues that I then have to deal with 😞

**Comment by josteinaj** [comment]
Oh, right, I didn't notice those existing PRs.

We're planning a new release of the nordic migrator, and the method we will recommend to install it (as we have done for previous versions) will be using the updater. We'll also have a Docker image, which many will use, but many will also prefer a native Windows (or possibly Linux) installation.

Is the nordic migrator the only real use case for the updater? When updating from for instance 1.14.3 to 1.14.4, does the .deb,  .msi and .dmg files upgrade properly without the updater?

Another way to install the nordic migrator could be to just drop the JAR file into the Pipeline 2 installation directory where all the other JARs are. That's what we do in the Dockerfile:

```Dockerfile
COPY --from=builder /usr/src/nordic-epub3-dtbook-migrator/target/nordic-epub3-dtbook-migrator-*.jar /opt/daisy-pipeline2/system/common/
```

I suppose that might cause problems in some instances if the user that installs it doesn't have permissions to write to that directory (typically in Windows), but maybe that's a limitation we can live with. Do you think that would be a better solution? Then you could deprecate the updater to lower the maintenance cost of Pipeline 2?

**Comment by bertfrees** [comment]
> We're planning a new release of the nordic migrator, and the method we will recommend to install it (as we have done for previous versions) will be using the updater.

Do you need the 1.14.2, 1.14.3 and 1.14.4 release descriptors for that though? Isn't all you need your custom release descriptor for the Nordic migrator? Wouldn't you recommend installing version 1.14.4 of Pipeline and then running the updater?

> When updating from for instance 1.14.3 to 1.14.4, does the .deb, .msi and .dmg files upgrade properly without the updater?

I don't quite understand the question.

> Another way to install the nordic migrator could be to just drop the JAR file into the Pipeline 2 installation directory where all the other JARs are.

Sure, that's always an option too.

> Is the nordic migrator the only real use case for the updater?

I don't know. I've used it some times in the past to make new versions available. But because the non-JAR files (configuration files and executables) have been changing a lot, it couldn't be used often, and if it can't be used consistently I think it's better to not use it at all.

**Comment by bertfrees** [comment]
Yes AFAIK the uninstallation happens automatically.

**Comment by josteinaj** [comment]
Ok. So not much use for the updater then. So from now on the decriptor is only really needed for the version attribute in /alive I guess.

**Comment by bertfrees** [comment]
The updater has potential for sure. But I think some issues need to be addressed before I'm going to use it more "officially". But for cases like installing the Nordic migrator it can already be useful.

**Comment by josteinaj** [comment]
Can ble closed as wontfix I think?

**Comment by bertfrees** [comment]
Yes.

**Pull request closed without merging**
