### PR TITLE
Don't build the NSIS installer in the dev-launcher profile

### LINKED ISSUE #126: NSIS fails when building dev-launcher
With pipeline-assembly v1.10.0, NSIS 3.01:

```
[INFO] --- nsis-maven-plugin:1.0-alpha-1:make (default) @ assembly ---
[INFO] [MAKENSIS] !include: could not find: "../project.nsh"
[INFO] [MAKENSIS] Error in script "target/nsis/installer.nsi" on line 35 -- aborting creation process
```

### PR DESCRIPTION
**Pull request by dkager**
Fixes #126.

### CODE REVIEW

**Comment by bertfrees** [comment]
Thanks. But will the backward slashes work on Mac/Linux?

**Comment by dkager** [comment]
I don't know. AFAIK that plugin is only enabled on Windows now, but I could be wrong. Some paths in the script already used backslashes.

**Comment by bertfrees** [comment]
If Romain or I want to build the installer we do it from MacOS so we enable the "win" profile explicitly.

But anyway I've checked and it still seems works with the backslashes.

**Comment by bertfrees** [comment]
Merged in https://github.com/daisy/pipeline-assembly/commit/b1065d7dab85fec03022e169d7719e7eabeb6402.

**Pull request closed without merging**
