### PR TITLE
Continuous integration of pipeline-assembly

### PR DESCRIPTION
**Pull request by bertfrees**
Automatically check that master is always working which makes it easy to release more regularly (i.e. intermediary releases, without announcement etc., possibly even snapshot releases).

Integration tests can be run with pipeline-it.

For unit tests we could write a script that inspects the latests BOMs and for each module goes and check out the right version and unit tests it with the version numbers of all the dependencies as defined in the BOMs. We discussed this new strategy a bit in Paris.

If possibly run the checks with Travis.

See also
- [x] https://github.com/daisy/pipeline-tasks/issues/8
- [x] https://github.com/daisy/pipeline-tasks/issues/23

### CODE REVIEW

**Comment by bertfrees** [comment]
@capitancambio I'm looking at https://github.com/daisy/pipeline-it/blob/3ae9db4130b39e5e3b0e78968d7cfc9f360d42c1/daisy/framework-integration/pom.xml#L115. Would it be possible to just get the assembly zip from the Maven repo and unzip, instead of bootstrapping the thing? This way we could call the integration tests from pipeline-assembly instead of the other way around?

**Comment by capitancambio** [comment]
Sure, I did it that way in order to test the tip, (If I recall correctly)
but either way is cool

cheers,

Javi

**Comment by bertfrees** [comment]
Can we merge this soonish?

**Comment by rdeltour** [comment]
@bertfrees first sorry for the late action on this :blush: 

Now, I'm trying to get that assembly branch building but it won't get some BoM dependencies, some versions of which are built from non-master branches (hence not available in our snapshot repo).
I'm looking to progressively merge other PRs to make this one build OK. See for instance daisy/pipeline-mod-braille#22

**Comment by bertfrees** [comment]
Yes that's right there are some dependencies on other commits which I referenced in the comments. I'll help you through it :)

**Comment by bertfrees** [comment]
This PR is outdated and partly not relevant anymore. Now that we have the super project and the dependencies have been clean up (https://github.com/daisy/pipeline/pull/503), and with the planned "full build" support (https://github.com/daisy/pipeline-tasks/issues/40), we have another way of running all the tests at once.

The Docker stuff could be extracted into a new branch. I'm creating a new issue for it: 

So I'll close the issue but for now keeping the branch around.

**Pull request closed without merging**
