### PR TITLE
Redhat rpm

### PR DESCRIPTION
**Pull request by alaram**
Two new maven profiles for PRM packaging:

daisy/pipeline-assembly#63

### CODE REVIEW

**Comment by bertfrees** [comment]
Thanks very much! Looks pretty good at first sight. A few comments/questions:

- The deb profile does filtering with inline profile properties and the centos profile does filtering with the dist.properties / dist-nix.properties files. I would like to harmonize that.
- I would like the profile to not be auto-activated. By The way does the RPM Maven plugin work on any machine or do you need to be on RedHat/CentOS?
- Can we have a separate RPM for the CLI, just like in the deb profile?
- I'll probably generate all RPM's (server + CLI + web UI) in a single profile, just like in the deb profile. Alternatively I can split the deb profile in a separate profile for each DEB. Was there a particular reason to do it like you did?
- Why does the webui RPM include the start.bat, uninstall and uninstall.bat? The uninstall scripts are for manual removal so shouldn't be needed in RPM packages, and BAT files are for Windows only AFAIK.
- You seem to give directories filemode 755. Why is that? And somewhere there is a 754, is that a typo?
- I haven't tested the resulting RPMs. I will rebase this PR on https://github.com/daisy/pipeline-assembly/pull/68 and add an automated test.

**Comment by alaram** [comment]
* The deb profile does filtering with inline profile properties and the centos profile does filtering with the dist.properties / dist-nix.properties files. I would like to harmonize that. --> How would you like to do that? In which way shall we help you to do it? Would you like us to that the same way like in the DEB profile?

* I would like the profile to not be auto-activated. By The way does the RPM Maven plugin work on any machine or do you need to be on RedHat/CentOS? --> I would search but I haven't check how to change the profile from auto-activated. The maven plugin works in any machine that can run rpmbuild package with its dependencies.

* Can we have a separate RPM for the CLI, just like in the deb profile? --> I think that is possible and I will go forward and do it when you confirm that you want it, too.

* I'll probably generate all RPM's (server + CLI + web UI) in a single profile, just like in the deb profile. Alternatively I can split the deb profile in a separate profile for each DEB. Was there a particular reason to do it like you did? --> I did two profiles which means just the server engine and also the Web UI separate just to make it modular but I would like you give me more detail on what you mean "particular reason to do it like you did".

* Why does the webui RPM include the start.bat, uninstall and uninstall.bat? The uninstall scripts are for manual removal so shouldn't be needed in RPM packages, and BAT files are for Windows only AFAIK. --> I will remove these files from this package since they indeed don't belong here so I will take them out for the coming version

* You seem to give directories filemode 755. Why is that? And somewhere there is a 754, is that a typo? --> I will fix it. They should be 644, that is the correct mode

* I haven't tested the resulting RPMs. I will rebase this PR on #68 and add an automated test --> Does this means that we should continue with our commits here, or? I will continue in this branch unless you said something different.


Thanks for the comments and I will do my changes asap and commit.

**Comment by bertfrees** [comment]
>> * The deb profile does filtering with inline profile properties and the centos profile does filtering with the dist.properties / dist-nix.properties files. I would like to harmonize that.
>
> How would you like to do that? In which way shall we help you to do it? Would you like us to that the same way like in the DEB profile?

Don't worry about it, I will take care of it.

>> * I would like the profile to not be auto-activated. By The way does the RPM Maven plugin work on any machine or do you need to be on RedHat/CentOS?
>
> I would search but I haven't check how to change the profile from auto-activated.

I'll remove the <activation> elements, to activate the profile just add the `-Pcentos` switch.

> The maven plugin works in any machine that can run rpmbuild package with its dependencies.

OK, so the RPM can be build on a Mac too as long as you have rpmbuild. Cool.

>> * Can we have a separate RPM for the CLI, just like in the deb profile?
>
> I think that is possible and I will go forward and do it when you confirm that you want it, too.

Yes, thanks.

>> * I'll probably generate all RPM's (server + CLI + web UI) in a single profile, just like in the deb profile. Alternatively I can split the deb profile in a separate profile for each DEB. Was there a particular reason to do it like you did?
>
> I did two profiles which means just the server engine and also the Web UI separate just to make it modular but I would like you give me more detail on what you mean "particular reason to do it like you did".

OK, let me think about it, I might change it later.

>> * I haven't tested the resulting RPMs. I will rebase this PR on #68 and add an automated test
>
> Does this means that we should continue with our commits here, or? I will continue in this branch unless you said something different.

Yes, please continue in this branch.

**Comment by alaram** [comment]
Hello,

I have added the CLI RPM packaging in a separate profile and verify that this is created and installed, I have updated the permissions for the user pipeline2 and I have removed the activation XML element so it works witn mvn -P <PROFILE> clean install for example.

The other changes that you have mentioned in the thread I have not done anything however I have tested locally but I will leave those to you as you mentioned before.

Please let me know when you manage to build and test this new commit.

Cheers!

**Comment by bertfrees** [comment]
Thank you, I'll create a test as soon as I can and if everything looks okay I'll ask Romain to merge.

**Comment by bertfrees** [comment]
I've pushed some additional changes to https://github.com/daisy/pipeline-assembly/commits/redhat_rpm. I also made a test for the server's RPM package, and it seems to work :smiley:  I'm waiting for https://github.com/daisy/pipeline-assembly/pull/68 before I push the test though.

I haven't tested the cli and webui packages.

One thing that isn't right with the server packages yet is that I get the following warnings:

    warning: user pipeline2 does not exist - using root
    warning: group pipeline2 does not exist - using root

So it's probably best to change pipeline.user and pipeline.group to root.

Something to note is that I couldn't build the RPM on my Mac, even after I installed rpmbuild with Homebrew. Not a big problem, I can use a VM or Docker. But we should maybe mention it in the README.

One peculiar thing (not an issue, just something I'd like to understand) is that I get stuff like this in the build log when building an RPM. What's up with that? Is rpmbuild OSGi-aware??

       Provides: osgi(ch.qos.logback.classic) = 1.0.11 osgi(ch.qos.logback.core) = 1.0.11
       osgi(com.google.guava) = 15.0.0 osgi(com.springsource.com.mysql.jdbc) = 5.1.6
       osgi(com.sun.jna) = 4 osgi(com.thaiopensource.jing) = 20120724.0.0 osgi(com.xmlcalabash) =
       1.0.23 osgi(javax.persistence) = 2.0.3 osgi(javax.servlet) = 2.5.0 osgi(jcl.over.slf4j) =
       1.7.2 osgi(jul.to.slf4j) = 1.7.2 osgi(net.sf.saxon.saxon-he) = 9.5.1
       osgi(nu.validator.htmlparser) = 1.4 osgi(org.apache.commons.codec) = 1.6.0
       osgi(org.apache.commons.fileupload) = 1.2.2 osgi(org.apache.commons.io) = 2.3.0
       osgi(org.apache.derby) = 10.8.2 osgi(org.apache.felix.configadmin) = 1.6.0
       osgi(org.apache.felix.dependencymanager) = 3.1.0 osgi(org.apache.felix.eventadmin) = 1.3.2
       osgi(org.apache.felix.fileinstall) = 3.2.6 osgi(org.apache.felix.gogo.command) = 0.14.0
       osgi(org.apache.felix.gogo.runtime) = 0.12.1 osgi(org.apache.felix.gogo.shell) = 0.10.0
       osgi(org.apache.felix.log) = 1.0.1 osgi(org.apache.felix.main) = 4.4.1
       osgi(org.apache.felix.metatype) = 1.0.6ine.modules.text-to-ssml) = 2.0.0
       osgi(org.daisy.pipeline.modules.tts-adapter-acapela) = 2.0.0
       osgi(org.daisy.pipeline.modules.tts-adapter-attbin) = 1.0.0
       osgi(org.daisy.pipeline.modules.tts-adapter-espeak) = 2.0.0
       osgi(org.daisy.pipeline.modules.tts-adapter-osx) = 2.0.0
       osgi(org.daisy.pipeline.modules.tts-adapter-sapinative) = 2.0.0
       osgi(org.daisy.pipeline.modules.tts-common) = 2.0.0
       osgi(org.daisy.pipeline.modules.validation-utils) = 1.0.1
       osgi(org.daisy.pipeline.modules.zedai-break-detection) = 1.1.0
       osgi(org.daisy.pipeline.modules.zedai-to-epub3) = 1.2.0
       osgi(org.daisy.pipeline.modules.zedai-to-html) = 1.0.2
       osgi(org.daisy.pipeline.modules.zedai-to-ssml) = 1.0.0
       osgi(org.daisy.pipeline.modules.zedai-utils) = 1.0.0
       osgi(org.daisy.pipeline.modules.zip-utils) = 1.1.0 osgi(org.daisy.pipeline.persistence-derby)
       = 2.0.0 osgi(org.daisy.pipeline.push-notifier) = 2.0.0 osgi(org.daisy.pipeline.webservice) =
       2.0.2 osgi(org.daisy.pipeline.webservice-utils) = 2.1.0
       osgi(org.daisy.pipeline.woodstox-osgi-adapter) = 2.0.0

**Comment by alaram** [comment]
Hello, 

I have updated and committed the pom.xml file and the change is in all the profiles which means root:root is user and group. In regards to MAC environments I have no clue since I have never tested there though I suppose that being debian based should work but I am no sure though, odd! Absolutetly I would recommend to add this on the README so people is aware of this, too.

Regarding the OSGi aware is something is have not realised but I will try to search but I have no answer right now for that!

**Comment by bertfrees** [comment]
Rebased onto https://github.com/daisy/pipeline-assembly/commits/redhat_rpm and added instructions to README.

@rdeltour LGTM

**Comment by bertfrees** [comment]
@joeha480 and @alaram: merged now in https://github.com/daisy/pipeline-assembly/commit/170f8e962bfad0f276e4456fe69b3425f37320b6

**Pull request closed without merging**
