### PR TITLE
Make the Makefile cross-platform

### PR DESCRIPTION
**Pull request by bertfrees**

### CODE REVIEW

**Comment by egli** [comment]
Just a minor nit pick: Couldn't you use the make from chocolatey?

Something along the lines of 
``` yaml
name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: choco install make
      - run: make.exe --version
```

**Comment by bertfrees** [comment]
Ah, I didn't know chocolatey had a make. But anyway, for my peace of mind it's better to have a fixed version of make, because different versions of make may behave differently. Actually I had to make some adjustments to the source code in order to make it work, I kind of doubt that the chocolatey version will work.

**Comment by egli** [comment]
> I had to make some adjustments to the source code in order to make it work

You changed the source code of GNU make?

> for my peace of mind it's better to have a fixed version of make, because different versions of make may behave differently

I understand your motivation, but to think that on windows the pipeline can only be built with a specific version of Make that has been modified does not evoke warm and cozy feelings. I generally prefer the simplest possible solution. But we've been through this before. I will not interfere with the pipeline build system :-)

**Comment by bertfrees** [comment]
> You changed the source code of GNU make?

Yes.

> to think that on windows the pipeline can only be built with a specific version of Make that has been modified does not evoke warm and cozy feelings

Well, I don't think I use any exotic make features (not even GNU Make specific). It just didn't work correctly on Windows so I believe it was a bug in GNU Make and that is the reason I patched it. I don't really see a problem with that. It works and I don't see a reason why it would suddenly stop working.

The other reason for including `make.exe` was to further reduce the number of build dependencies.

I admit the Makefile is not as simple as it could be, but that is not because I made it cross-platform.

**Pull request merged**
